### DISCUSSION TITLE
Trouble running a pwsh command with wsl

### DISCUSSION THREAD

**Discussion by ssbarnea** [Vampire/setup-wsl#37] [General]
I am currently trying to create a symlinked directory inside the GITHUB_WORKSPACE that goes into the linux home directory, so we avoid the /mnt permission problems during our build and testing.

Still, while I was able to run the commands locally, something upsets GHA task and refuses to create the folder.

![](https://sbarnea.com/ss/Screen-Shot-2022-07-01-12-03-44.33.png)

AFAIK, there is nothing wrong with `mkdir -p "$wsl_home\ws"`, it appears to work fine locally.

The [GHA task](https://github.com/ansible/ansible-language-server/runs/7148659678?check_suite_focus=true0 looks more like:
```
      - shell: pwsh # <-- needed in order override the implicit wsl wrapper
        run: |
          $wsl_home=wsl --cd ~ --exec wslpath -w .;
          echo "$wsl_home";
          mkdir -p "$wsl_home\ws";
          mklink -D ws "$wsl_home\ws";
          echo "::set-output name=working-directory::$wsl_home\ws"
```

**Comment by Vampire** [comment]
Without having it tried, I think the problem it complains about is the `$` in the path.
I would guess this is just a followup problem of "The system cannot find the file specified", which maybe means the first line did not actually execute properly?
I also do not see the output of the `echo`.

**Reply by Vampire** [reply]
Yep, just doing
```yml
jobs:
    foo:
        runs-on: windows-2019
        steps:
            - shell: pwsh #
              run: wsl --cd ~ --exec wslpath -w .
```
Already gives
```bash
The system cannot find the file specified.
```
And
```yml
jobs:
    foo:
        runs-on: windows-2019
        steps:
            - shell: pwsh #
              run: wsl --cd ~ --exec wslpath -w .
```
shows that there is no `--cd` option:
```plain
Usage: wsl.exe [option] ...


Options:


    -d, --distribution <DistributionName>


        Launch the specified distribition.





    -e, --exec <CommandLine>


        Execute the specified Linux command. The remainder of the arguments are


        used as the command line to execute.





    -u, --user <UserName>


        Run as the specified user.





    --help


        Display this usage information.





    --


        Stop parsing arguments and pass the remainder to the Linux process.
```

Even the wsl v2 wsl.exe on windows-2022 does not have the `--cd` option.
