### DISCUSSION TITLE
actions/checkout path to WSL

### DISCUSSION THREAD

**Discussion by scivision** [Vampire/setup-wsl#51] [Q&A] [answered]
I want to run a CMake project in WSL, but have trouble programmatically finding the top-level project source directory. I didn't quite get how to do this from the existing setup-wsl Discussions.

Here is a failed run: https://github.com/scivision/detect-windows-subsystem-for-linux/actions/runs/7023130945/job/19108936615

The log:

```
Run cmake -S $(wslpath -u ${GITHUB_WORKSPACE}) -Bbuild
  cmake -S $(wslpath -u ${GITHUB_WORKSPACE}) -Bbuild
  shell: D:\a\_temp\wsl-shell-wrapper\wsl-bash.BAT {0}
  env:
    CTEST_NO_TESTS_ACTION: error
    WSLENV: GITHUB_WORKSPACE
CMake Error: The source directory "/mnt/d/a/detect-windows-subsystem-for-linux/detect-windows-subsystem-for-linux" does not appear to contain CMakeLists.txt.
```

The yaml:

```yaml
 wsl:
    runs-on: windows-latest

    env:
      WSLENV: GITHUB_WORKSPACE

    defaults:
      run:
          shell: wsl-bash {0}

    steps:
    - uses: Vampire/setup-wsl@v2
      with:
        additional-packages:
          cmake make gcc g++

    - run: cmake -S $(wslpath -u ${GITHUB_WORKSPACE}) -Bbuild
    - run: cmake --build build
    - run: ctest --test-dir build -V
```
