### DISCUSSION TITLE
Executing script instead of command list

### DISCUSSION THREAD

**Discussion by lepapareil** [Vampire/setup-wsl#63] [General]
Hi `wsl` masters 😃, 

When I try to exec `test.sh` instead of commands list, I get this error:

```
bash: line 2: set: pipefail
  : invalid option name
```

Here is my `job` definition:

```
jobs:
  test-windows-wsl-x64:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.1
    - name: Setup WSL
      uses: Vampire/setup-wsl@v3.1.3
      with:
        distribution: Ubuntu-22.04
    - shell: wsl-bash {0}
      run: |
          cd "/mnt/$(echo "${{ github.workspace }}" | tr -d ':'  | tr '\\' '/' | tr '[:upper:]' '[:lower:]')"
          test.sh
```

And `test.sh`:

```
#!/bin/bash
set -Eeuo pipefail
echo "test"
```
