### DISCUSSION TITLE
Cannot set environment variables with env:

### DISCUSSION THREAD

**Discussion by skirmess** [Vampire/setup-wsl#9] [Q&A] [answered]
The following workflow

```
name: test
on: push
jobs:
  wsl1:
    name: WSL1
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - distribution: 'Ubuntu-20.04'

    defaults:
      run:
        shell: wsl-bash {0}

    steps:
      - uses: Vampire/setup-wsl@v1
        with:
          distribution: ${{ matrix.distribution }}

      - run: echo $TEST_ENV
        env:
          TEST_ENV: 17
```

produces the following error

```
Run echo $TEST_ENV
  echo $TEST_ENV
  shell: D:\a\_temp\wsl-shell-wrapper\wsl-bash.BAT {0}
  env:
    TEST_ENV: 17
/mnt/d/a/_temp/08e7af50-f443-48aa-8385-def712c2f327: line 1: TEST_ENV: unbound variable
Error: Process completed with exit code 1.
```

**Comment by Vampire** [comment, marked as answer]
This is normal WSL behavior.
Almost no environment variables are forwarded from Windows to WSL by default.
You need to use `WSLENV` to configure which environment variables are forwarded and how they should be converted (path, list of paths, plain, ...).
In your example if you add `WSLENV: TEST_ENV` as environment variable, it runs through as expected.

**Reply by skirmess** [reply]
That worked perfectly, thanks.

In case someone else finds this. The variable takes a colon separated list of environment variables to allow. Like so:

```
  wsl1:
    runs-on: windows-latest

    env:
      TAR_OPTIONS: --warning=no-unknown-keyword
      WSLENV: AUTOMATED_TESTING:PERL_USE_UNSAFE_INC:TAR_OPTIONS

    defaults:
      run:
        shell: wsl-bash {0}

    steps:
      - uses: actions/checkout@v2
        with:
          path: ${{ github.event.repository.name }}

      - uses: Vampire/setup-wsl@v1
        with:
          distribution: ${{ matrix.distribution }}
          additional-packages: ${{ matrix.packages }}

      - name: perl Makefile.PL
        run: perl Makefile.PL
        working-directory: ${{ github.event.repository.name }}
        env:
          AUTOMATED_TESTING: 1
          PERL_USE_UNSAFE_INC: 0
```
