### ISSUE TITLE
Support Windows 2022

### ISSUE THREAD

**Issue by mchernyavsky** [Vampire/setup-wsl#15]
I have a workflow with the following configuration:

```yaml
name: test

on:
    push:
    pull_request:

jobs:
    test:
        runs-on: windows-2022
        timeout-minutes: 60

        steps:
            - uses: actions/checkout@v2

            - name: Set up WSL
              uses: Vampire/setup-wsl@v1
              with:
                  distribution: Ubuntu-18.04
                  additional-packages: cargo

            - name: Check environment
              shell: wsl-bash {0}
              run: |
                  which rustc
                  rustc --version
                  which cargo
                  cargo install --list

            - name: Build
              shell: wsl-bash {0}
              run: cargo build

            - name: Test
              shell: wsl-bash {0}
              run: cargo test

            - name: Run
              shell: wsl-bash {0}
              run: cargo run

            - name: Finish check
              run: echo "Check finished successfully!"
```

It hangs on `Set up WSL` step for some reason:
https://github.com/mchernyavsky/test-wsl/actions/runs/1556841968

I'm not sure what the problem is, but if I change environment to `windows-2019` everything works just fine:
https://github.com/mchernyavsky/test-wsl/actions/runs/1556805202
