### ISSUE TITLE
windows-latest: ` Error: This Windows environment does not have WSL enabled, please verify your 'runs-on' setting`

### ISSUE THREAD

**Issue by jansorg** [Vampire/setup-wsl#48]
With `runs-on: windows-latest` I'm now getting the following error. I think it was working in the past, but I'm not entirely sure.
Did the action change or perhaps the setup of the windows-latest runner?
Thank you for your work on this action -- it's very helpful! :) 

```
Run Vampire/setup-wsl@v2
Verify Windows Environment
Error: This Windows environment does not have WSL enabled, please verify your 'runs-on' setting
```

My job setup:
```yaml
      - name: Install WSL distribution
        uses: Vampire/setup-wsl@v2
        with:
          distribution: Ubuntu-22.04
          use-cache: 'true'

```

Runner system info:
![image](https://github.com/Vampire/setup-wsl/assets/11473063/63cc8a76-5d20-4ee7-b2a9-7bfcc5e0118c)
