### ISSUE TITLE
Document crlf glitches

### ISSUE THREAD

**Issue by kousu** [Vampire/setup-wsl#5]
Hi! First, let me just say: THANK YOU SO MUCH FOR THIS. It's saved me a ton of time already.

While implementing testing on WSL, I ran into the bizarre error `./.ci.sh: line 4: $'\r': command not found`, e.g. https://github.com/neuropoly/spinalcordtoolbox/runs/1606955337?check_suite_focus=true from https://github.com/neuropoly/spinalcordtoolbox/blob/af36bdedc2ee789a370f101bfec868cdd7ea1e76/.ci.sh.

This is because this runs Linux *on top of* Windows, so `actions/checkout@v2` mangles the line-endings and then Linux sees `\r`s and gets confused. To fix this, I needed to force `core.autocrlf` off:
```
    steps:
    - uses: Vampire/setup-wsl@v1
      with:
        distribution: ${{matrix.container}}
    - name: Use unix line endings
      shell: bash
      run: |
        # Github's actions/checkout@v2 when run on Windows mangles the line-endings to DOS-style
        # but we're running Linux *on top* of Windows, so we need to not mangle them!
        # https://github.com/actions/checkout/issues/135#issuecomment-602171132
        # https://github.com/actions/virtual-environments/issues/50#issuecomment-663920265
        git config --global core.autocrlf false
        git config --global core.eol lf
```

There's an open bug about it: https://github.com/actions/checkout/issues/135 / https://github.community/t/git-config-core-autocrlf-should-default-to-false/16140/7 but Github doesn't seem interested in fixing it; I bet this is a pretty common gotcha specifically when using WSL, so do you think you could document it in your docs? I see you're [very aware of the issue](https://github.com/actions/virtual-environments/issues/50#issuecomment-663921024) but I had no clue I would run into it, or especially that I needed to add `shell: bash` to [the suggested fix](https://github.com/actions/checkout/issues/135#issuecomment-602171132) counteract [your advice to set the default shell to wsl](https://github.com/marketplace/actions/setup-wsl#default-shell).

I see [people](https://github.com/actions/checkout/issues/135#issuecomment-613361104) in those threads, [including you](https://github.com/actions/virtual-environments/issues/50#issuecomment-663921024), recommending `.gitattributes`. In my case, maybe something like this would have done:

```
# .gitattributes
*.sh text eol=lf
```

That's certainly *a* fix, but my problem comes narrowly from trying to layer Linux on top of Windows, and with docker in the mix. In 99.99% of WSL installs, our users are going to be installing using git from *inside WSL*, so the glitch will never show up. It's only because CI's `actions/checkout@v2` is running in its own container-on-Windows and deciding that that means it should mangle line endings, so I would rather counteract it in our CI script instead of doing it project-wide.
