### ISSUE TITLE
wsl-shell-command debugging

### ISSUE THREAD

**Issue by jmoguillansky-gpsw** [Vampire/setup-wsl#6]
Hi,
currently wsl-shell is invoked with the default wsl-shell-command: bash --noprofile --norc -euo pipefail
The -u means that bash will report an error if a variable is "unbounded".
It might be helpful to add some extra log output if the bash command fails?
I ran into an issue where my bash script failed (because of an unbound variable) but the setup-wsl action didn't really show much debug output?

Also, may want to add -x param by default (to simplify debugging)?

**Comment by Vampire** [comment]
> It might be helpful to add some extra log output if the bash command fails?
I ran into an issue where my bash script failed (because of an unbound variable) but the setup-wsl action didn't really show much debug output?

I'm not sure what more you want than the default bash output.

I run this workflow:
```yaml
name: Foo
on: push
jobs:
    foo:
        runs-on: windows-latest

        steps:
            - name: Activate WSL1
              uses: Vampire/setup-wsl@v1

            - run: echo $foo
              shell: wsl-bash {0}
```
And the result is the imho pretty clear
```
Run echo $foo
  echo $foo
  shell: D:\a\_temp\wsl-shell-wrapper\wsl-bash.BAT {0}
/mnt/d/a/_temp/c29c0bd4-415c-4480-8e8b-c40c09524360: line 1: foo: unbound variable
Error: Process completed with exit code 1.
```

> Also, may want to add -x param by default (to simplify debugging)?

Sorry, but I don't like that idea.
As you just said yourself, this is a debugging option.
It has imho no justification to be in production usage, at least not by default.
If you want that for your workflows, you can easily add it using the `wsl-shell-command` input like
```yml
- name: Activate WSL1
  uses: Vampire/setup-wsl@v1
  with:
      wsl-shell-command: bash --noprofile --norc -euxo pipefail
```
