### ISSUE TITLE
Feature request to configure /etc/wsl.conf

### ISSUE THREAD

**Issue by kai2nenobu** [Vampire/setup-wsl#7]
This is a feature request to configure `/etc/wsl.conf` for WSL distribution.

I want to mount DrvFs (Windows file systems under `/mnt`) by `wsl-shell-user` but  WSL distribution mounts them by root user.

To change this behavior, it requires a manual step to change mount options in `/etc/wsl.conf` and restart the distribution after `Vampire/setup-wsl` step like below. ([my workflow sample](https://github.com/kai2nenobu/github_actions_trial/blob/42e7e6399ed24fa4e04754fcfbe8451165a2b993/.github/workflows/wsl.yml#L13-L31) and [workflow result](https://github.com/kai2nenobu/github_actions_trial/runs/2224251664))

```yaml
      - uses: Vampire/setup-wsl@v1
        with:
          distribution: Ubuntu-20.04
          set-as-default: 'true'
          wsl-shell-user: wsl
      - name: Change mount options and restart
        shell: powershell
        run: |
          wsl -u root bash -c "printf '[automount]\nenabled = true\noptions = `"metadata,uid=1000,gid=1000,umask=22,fmask=11`"\n' | tee /etc/wsl.conf"
          wslconfig /terminate Ubuntu-20.04
```

If `Vampire/setup-wsl` has a feature to directly configure `/etc/wsl.conf`, it makes things simple and easy.

```yaml
      - uses: Vampire/setup-wsl@v1
        with:
          distribution: Ubuntu-20.04
          set-as-default: 'true'
          wsl-shell-user: wsl
          # configure /etc/wsl.conf ("wsl-conf" is just an example)
          wsl-conf: |
            [automount]
            enabled = true
            options = "metadata,uid=1000,gid=1000,umask=22,fmask=11"
```

Please consider to add this feature if you like.
