### ISSUE TITLE
Cannot set environment variables with env:

### ISSUE THREAD

**Issue by skirmess** [Vampire/setup-wsl#8]
The following workflow

```
name: test
on: push
jobs:
  wsl1:
    name: WSL1
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - distribution: 'Ubuntu-20.04'

    defaults:
      run:
        shell: wsl-bash {0}

    steps:
      - uses: Vampire/setup-wsl@v1
        with:
          distribution: ${{ matrix.distribution }}

      - run: echo $TEST_ENV
        env:
          TEST_ENV: 17
```

produces the following error

```
Run echo $TEST_ENV
  echo $TEST_ENV
  shell: D:\a\_temp\wsl-shell-wrapper\wsl-bash.BAT {0}
  env:
    TEST_ENV: 17
/mnt/d/a/_temp/08e7af50-f443-48aa-8385-def712c2f327: line 1: TEST_ENV: unbound variable
Error: Process completed with exit code 1.
```
